name: Continuous integration
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the sources
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install the dependencies
        run: npm install --ignore-scripts
      - name: Run the tests
        env:
          NODE_OPTIONS: '--experimental-modules --no-warnings'
        run: npm test
      - name: Collect the code coverage
        env:
          CI: true
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_OPTIONS: '--experimental-modules --no-warnings'
        if: success()
        run: |
          npm run-script prepack
          npm run-script coverage
